---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box


suites:
- name: default
  run_list:
  - recipe[keepalived_test::default]
  - recipe[keepalived_test::configured]
  attributes: {developer_mode: true}
