name             'keepalived'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs and configures keepalived'
source_url       'https://github.com/sous-chefs/keepalived'
issues_url       'https://github.com/sous-chefs/keepalived/issues'
chef_version     '>= 15.3'
version          '6.0.21'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'oracle'
supports 'amazon'
